solver:
  optimizer:
    name: 'SGD'
    momentum: 0.9
  regularization:
    weight_decay: 0.0001
  lr:
    policy: 'exp'
    base_lr: 0.1
    gamma: 0.1
    stepvalue: 200000
  extra:
    global_step: -1
    adjust_lr: []
    update_var_scope:
recoverer:
  pretrained_model:
  # pretrained_model: 'ckpt-contextdesc/model-5500.hdf5'
  # pretrained_model: 'ckpt-contextdesc/model.ckpt-800000'
  # pretrained_model: '/media/gidobot/data/contextdesc/pretrained/contextdesc++/model.ckpt-400000'
  ckpt_step:
  # exclude_var: 'deform_param,Momentum,scale_temperature'
  exclude_var:
dump:
  snapshot: 10000
  display: 20
  max_steps: 400000
  log_dir: 'log'
network:
  quantize: false
  quantize_aware: false
  loss_type: 'LOG'
  photaug: true
  dense_desc: false
  resize: -1
  use_corr_n: -1
  deform_desc: 0
  sift: false
  aug:
    # Geometric context
    geo_context: false
    kpt_m: 1.0
    # Visual context
    vis_context: false
    vis_feat_reso: 14
    vis_feat_dim: 2048
  det:
    weight: -1
